package StringProblems.Leetcode.Easy;

import java.util.Scanner;

public class findDiff {
    /*
     * 389: Find the Difference
     * 
     * You are given two strings s and t.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Return the letter that was added to t.
     * 
     * Constraints:
     *  0 <= s.length <= 1000
     *  t.length == s.length + 1
     *  s and t consist of lowercase English letters.
     * 
     * Example 1:
     *  Input: s = "abcd", t = "abcde"
     *  Output: "e"
     *  Explanation: 'e' is the letter that was added.
     * 
     * Example 2:
     *  Input: s = "", t = "y"
     *  Output: "y"
     * 
     */
    static char findDifference(String s, String t){
        int total = 0;

        for(int i=0; i<t.length(); i++){
            total = total + t.charAt(i);
        }

        for(int i=0; i<s.length(); i++){
            total = total - s.charAt(i);
        }

        return (char)total;
    }

    static char findDifferenceXOR(String s, String t){
        char c = 0;
        for(char cs : s.toCharArray()) c ^= cs;
        for(char ct : t.toCharArray()) c ^= ct;
        return c;
    }

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        String s = scan.nextLine();
        String t = scan.nextLine();
        scan.close();

        char extrachar = findDifference(s, t);
        System.out.println(extrachar);

        char extracharxor = findDifferenceXOR(s, t);
        System.out.println(extracharxor);
        
    }
}
